/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { IhelperLogic, IhelperLogicInterface } from "../IhelperLogic";

const _abi = [
  {
    inputs: [],
    name: "jointExecution",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IhelperLogic__factory {
  static readonly abi = _abi;
  static createInterface(): IhelperLogicInterface {
    return new utils.Interface(_abi) as IhelperLogicInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IhelperLogic {
    return new Contract(address, _abi, signerOrProvider) as IhelperLogic;
  }
}
