/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { IStabilizer, IStabilizerInterface } from "../IStabilizer";

const _abi = [
  {
    inputs: [],
    name: "goStabilizer",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IStabilizer__factory {
  static readonly abi = _abi;
  static createInterface(): IStabilizerInterface {
    return new utils.Interface(_abi) as IStabilizerInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IStabilizer {
    return new Contract(address, _abi, signerOrProvider) as IStabilizer;
  }
}
