/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { ITWAPOracle, ITWAPOracleInterface } from "../ITWAPOracle";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "tokenToPrice_",
        type: "address",
      },
      {
        internalType: "address",
        name: "tokenForPriceComparison_",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "epochPeriod_",
        type: "uint256",
      },
    ],
    name: "priceTokenAddressForPricingTokenAddressForLastEpochUpdateBlockTimstamp",
    outputs: [
      {
        internalType: "uint32",
        name: "",
        type: "uint32",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
      {
        internalType: "address",
        name: "",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    name: "pricedTokenForPricingTokenForEpochPeriodForLastEpochPrice",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
      {
        internalType: "address",
        name: "",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    name: "pricedTokenForPricingTokenForEpochPeriodForPrice",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    name: "uniV2CompPairAddressForLastEpochUpdateBlockTimstamp",
    outputs: [
      {
        internalType: "uint32",
        name: "",
        type: "uint32",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "uniV2CompatPairAddressToUpdate_",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "eopchPeriodToUpdate_",
        type: "uint256",
      },
    ],
    name: "updateTWAP",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class ITWAPOracle__factory {
  static readonly abi = _abi;
  static createInterface(): ITWAPOracleInterface {
    return new utils.Interface(_abi) as ITWAPOracleInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ITWAPOracle {
    return new Contract(address, _abi, signerOrProvider) as ITWAPOracle;
  }
}
