/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { IUSC, IUSCInterface } from "../IUSC";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "burn",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "account_",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount_",
        type: "uint256",
      },
    ],
    name: "mint",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IUSC__factory {
  static readonly abi = _abi;
  static createInterface(): IUSCInterface {
    return new utils.Interface(_abi) as IUSCInterface;
  }
  static connect(address: string, signerOrProvider: Signer | Provider): IUSC {
    return new Contract(address, _abi, signerOrProvider) as IUSC;
  }
}
